#!/usr/bin/env bash
# Short script to fix Nginx listening on port 80

apt-get update
apt-get install -y nginx
sed -i 's/listen 80 default_server;/listen 80 default_server;/g' /etc/nginx/sites-available/default
service nginx start

